language: swift
osx_image: xcode9

script:
  - xcodebuild -scheme ContinuousIntegration -workspace Watchlist.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)